name: Run Cron Job

on:
  schedule:
    - cron: "0 12 * * *" # Runs at 12 PM UTC daily

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call Express API
        run: curl -X GET https://fxglobal-backend.vercel.app/api/v1/run-cron
